# Generated by Django 5.0.3 on 2024-06-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='activ',
            new_name='active',
        ),
    ]
